SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS DEPENDENTE;
DROP TABLE IF EXISTS TRABALHA_EM;
DROP TABLE IF EXISTS PROJETO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS DEPTOS_LOCALIZACOES;
DROP TABLE IF EXISTS EMPREGADO;

SET FOREIGN_KEY_CHECKS = 1;

-- CRIAÇÃO DE TABELAS

CREATE TABLE DEPARTAMENTO (
    DNUMERO INT NOT NULL PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL,
    GERSSN CHAR(9),
    GERDATANICIO DATE
);

CREATE TABLE EMPREGADO (
    SSN CHAR(9) NOT NULL PRIMARY KEY,
    PNOME VARCHAR(50) NOT NULL,
    MINICIAL CHAR(1),
    UNOME VARCHAR(50) NOT NULL,
    DATANASC DATE,
    ENDERECO VARCHAR(200),
    SEXO CHAR(1),
    SALARIO DECIMAL(10,2),
    SUPERSSN CHAR(9),
    DNO INT,
    FOREIGN KEY (SUPERSSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE DEPTOS_LOCALIZACOES (
    DNUMERO INT NOT NULL,
    DLOCALIZACAO VARCHAR(100) NOT NULL,
    PRIMARY KEY (DNUMERO, DLOCALIZACAO),
    FOREIGN KEY (DNUMERO) REFERENCES DEPARTAMENTO(DNUMERO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PROJETO (
    PNUMERO INT NOT NULL PRIMARY KEY,
    PJNOME VARCHAR(50) NOT NULL,
    PLOCALIZACAO VARCHAR(100),
    DNUM INT,
    FOREIGN KEY (DNUM) REFERENCES DEPARTAMENTO(DNUMERO)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE TRABALHA_EM (
    ESSN CHAR(9) NOT NULL,
    PNO INT NOT NULL,
    HORAS DECIMAL(5,2),
    PRIMARY KEY (ESSN, PNO),
    FOREIGN KEY (ESSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PNO) REFERENCES PROJETO(PNUMERO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DEPENDENTE (
    ESSN CHAR(9) NOT NULL,
    NOME_DEPENDENTE VARCHAR(50) NOT NULL,
    SEXO CHAR(1),
    DATANASC DATE,
    PARENTESCO VARCHAR(20),
    PRIMARY KEY (ESSN, NOME_DEPENDENTE),
    FOREIGN KEY (ESSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Adicionando FKs que fecham o ciclo
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT fk_departamento_gerente
FOREIGN KEY (GERSSN) REFERENCES EMPREGADO(SSN)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE EMPREGADO
ADD CONSTRAINT fk_empregado_departamento
FOREIGN KEY (DNO) REFERENCES DEPARTAMENTO(DNUMERO)
ON UPDATE CASCADE ON DELETE SET NULL;

-- INSERÇÕES

-- Departamentos
INSERT INTO DEPARTAMENTO (DNUMERO, DNAME, GERSSN, GERDATANICIO) VALUES
(1, 'RH', NULL, NULL),
(5, 'TI', NULL, NULL),
(10, 'Marketing', NULL, NULL);

-- Empregados
INSERT INTO EMPREGADO (SSN, PNOME, MINICIAL, UNOME, DATANASC, ENDERECO, SEXO, SALARIO, SUPERSSN, DNO) VALUES
('111111111', 'Alice', 'B', 'Silva', '1990-05-01', 'Rua A, 100', 'F', 3000.00, NULL, 5),
('222222222', 'Bob', 'C', 'Santos', '1985-08-12', 'Rua B, 200', 'M', 4000.00, '111111111', 5),
('333333333', 'Carlos', 'D', 'Oliveira', '1992-02-20', 'Rua C, 300', 'M', 3500.00, '111111111', 5),
('444444444', 'Diana', 'E', 'Costa', '1995-07-15', 'Rua D, 400', 'F', 2800.00, '222222222', 1),
('555555555', 'Franklin', 'F', 'Wong', '1980-01-10', 'Rua E, 500', 'M', 5000.00, NULL, 10),
('666666666', 'Eva', 'G', 'Lima', '1993-09-23', 'Rua F, 600', 'F', 4200.00, '555555555', 10);

-- Definindo gerentes após a inserção de empregados
UPDATE DEPARTAMENTO SET GERSSN = '111111111', GERDATANICIO = '2020-01-01' WHERE DNUMERO = 5;
UPDATE DEPARTAMENTO SET GERSSN = '222222222', GERDATANICIO = '2021-06-15' WHERE DNUMERO = 1;
UPDATE DEPARTAMENTO SET GERSSN = '555555555', GERDATANICIO = '2019-09-10' WHERE DNUMERO = 10;

-- Dependentes
INSERT INTO DEPENDENTE (ESSN, NOME_DEPENDENTE, SEXO, DATANASC, PARENTESCO) VALUES
('111111111', 'Alice', 'F', '2015-06-10', 'Filha'),
('222222222', 'Carlos', 'M', '2010-04-22', 'Filho'),
('333333333', 'Diana', 'F', '2018-11-30', 'Filha');

-- Projetos
INSERT INTO PROJETO (PNUMERO, PJNOME, PLOCALIZACAO, DNUM) VALUES
(100, 'Produtox', 'Sede', 5),
(200, 'Alpha', 'Filial', 5),
(300, 'Beta', 'Sede', 10);

-- Trabalha_em
INSERT INTO TRABALHA_EM (ESSN, PNO, HORAS) VALUES
('111111111', 100, 12),
('111111111', 200, 5),
('111111111', 300, 8),
('222222222', 100, 8),
('222222222', 200, 5),
('333333333', 100, 10),
('444444444', 200, 7),
('555555555', 300, 6);

-- CONSULTAS

-- a) Empregados do departamento 5 que trabalham mais de 10 horas no projeto 'Produtox'
SELECT e.PNOME, e.MINICIAL, e.UNOME, e.DNO AS DEPARTAMENTO, p.PJNOME AS PROJETO, t.HORAS
FROM EMPREGADO AS e
JOIN TRABALHA_EM t ON e.SSN = t.ESSN
JOIN PROJETO p ON t.PNO = p.PNUMERO
WHERE e.DNO = 5 AND p.PJNOME = 'Produtox' AND t.HORAS > 10;

-- b) Empregados que têm dependente com mesmo primeiro nome
SELECT e.PNOME, e.MINICIAL, e.UNOME, d.NOME_DEPENDENTE, d.PARENTESCO
FROM EMPREGADO AS e
JOIN DEPENDENTE d ON e.SSN = d.ESSN
WHERE e.PNOME = d.NOME_DEPENDENTE;

-- c) Empregados supervisionados por 'Franklin Wong'
SELECT e.PNOME, e.MINICIAL, e.UNOME, s.PNOME AS SUPERVISOR, s.UNOME AS SOBRENOME_SUPERVISOR
FROM EMPREGADO AS e
JOIN EMPREGADO AS s ON e.SUPERSSN = s.SSN
WHERE s.PNOME = 'Franklin' AND s.UNOME = 'Wong';

-- d) Para cada projeto, liste o nome e o total de horas gastas
SELECT p.PJNOME, SUM(t.HORAS) AS TOTAL_HORAS
FROM PROJETO AS p
LEFT JOIN TRABALHA_EM AS t ON p.PNUMERO = t.PNO
GROUP BY p.PJNOME;

-- e) Empregados que trabalham em todos os projetos
SELECT e.PNOME, e.MINICIAL, e.UNOME, COUNT(DISTINCT t.PNO) AS QTDE_PROJETOS
FROM EMPREGADO AS e
JOIN TRABALHA_EM AS t ON e.SSN = t.ESSN
GROUP BY e.SSN
HAVING COUNT(DISTINCT t.PNO) = (SELECT COUNT(*) FROM PROJETO);

-- f) Empregados que não trabalham em nenhum projeto
SELECT e.PNOME, e.MINICIAL, e.UNOME, e.DNO AS DEPARTAMENTO
FROM EMPREGADO AS e
LEFT JOIN TRABALHA_EM t ON e.SSN = t.ESSN
WHERE t.ESSN IS NULL;

-- g) Para cada departamento, nome e média salarial (inclui departamentos sem empregados)
SELECT d.DNAME, AVG(e.SALARIO) AS MEDIA_SALARIAL, COUNT(e.SSN) AS QTD_EMPREGADOS
FROM DEPARTAMENTO AS d
LEFT JOIN EMPREGADO AS e ON d.DNUMERO = e.DNO
GROUP BY d.DNAME;

-- h) Média salarial dos empregados do sexo feminino
SELECT SEXO, AVG(SALARIO) AS MEDIA_SALARIAL
FROM EMPREGADO
WHERE SEXO = 'F';
EXERCÍCIO 02

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS DEPENDENTE;
DROP TABLE IF EXISTS TRABALHA_EM;
DROP TABLE IF EXISTS PROJETO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS DEPTOS_LOCALIZACOES;
DROP TABLE IF EXISTS EMPREGADO;

SET FOREIGN_KEY_CHECKS = 1;

-- CRIAÇÃO DE TABELAS

CREATE TABLE EMPREGADO (
    SSN CHAR(9) NOT NULL PRIMARY KEY,
    PNOME VARCHAR(50) NOT NULL,
    MINICIAL CHAR(1),
    UNOME VARCHAR(50) NOT NULL,
    DATANASC DATE,
    ENDERECO VARCHAR(200),
    SEXO CHAR(1),
    SALARIO DECIMAL(10,2),
    SUPERSSN CHAR(9),
    DNO INT,
    FOREIGN KEY (SUPERSSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE DEPARTAMENTO (
    DNUMERO INT NOT NULL PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL,
    GERSSN CHAR(9),
    GERDATANICIO DATE,
    FOREIGN KEY (GERSSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE DEPTOS_LOCALIZACOES (
    DNUMERO INT NOT NULL,
    DLOCALIZACAO VARCHAR(100) NOT NULL,
    PRIMARY KEY (DNUMERO, DLOCALIZACAO),
    FOREIGN KEY (DNUMERO) REFERENCES DEPARTAMENTO(DNUMERO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PROJETO (
    PNUMERO INT NOT NULL PRIMARY KEY,
    PJNOME VARCHAR(50) NOT NULL,
    PLOCALIZACAO VARCHAR(100),
    DNUM INT,
    FOREIGN KEY (DNUM) REFERENCES DEPARTAMENTO(DNUMERO)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE TRABALHA_EM (
    ESSN CHAR(9) NOT NULL,
    PNO INT NOT NULL,
    HORAS DECIMAL(5,2),
    PRIMARY KEY (ESSN, PNO),
    FOREIGN KEY (ESSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PNO) REFERENCES PROJETO(PNUMERO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DEPENDENTE (
    ESSN CHAR(9) NOT NULL,
    NOME_DEPENDENTE VARCHAR(50) NOT NULL,
    SEXO CHAR(1),
    DATANASC DATE,
    PARENTESCO VARCHAR(20),
    PRIMARY KEY (ESSN, NOME_DEPENDENTE),
    FOREIGN KEY (ESSN) REFERENCES EMPREGADO(SSN)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- INSERÇÕES

-- Departamentos
INSERT INTO DEPARTAMENTO (DNUMERO, DNAME, GERSSN, GERDATANICIO) VALUES
(1, 'RH', NULL, NULL),
(5, 'TI', NULL, NULL),
(10, 'Marketing', NULL, NULL);

-- Empregados
INSERT INTO EMPREGADO (SSN, PNOME, MINICIAL, UNOME, DATANASC, ENDERECO, SEXO, SALARIO, SUPERSSN, DNO) VALUES
('111111111', 'Alice', 'B', 'Silva', '1990-05-01', 'Rua A, 100', 'F', 3000.00, NULL, 5),
('222222222', 'Bob', 'C', 'Santos', '1985-08-12', 'Rua B, 200', 'M', 4000.00, '111111111', 5),
('333333333', 'Carlos', 'D', 'Oliveira', '1992-02-20', 'Rua C, 300', 'M', 3500.00, '111111111', 5),
('444444444', 'Diana', 'E', 'Costa', '1995-07-15', 'Rua D, 400', 'F', 2800.00, '222222222', 1),
('555555555', 'Franklin', 'F', 'Wong', '1980-01-10', 'Rua E, 500', 'M', 5000.00, NULL, 10),
('666666666', 'Eva', 'G', 'Lima', '1993-09-23', 'Rua F, 600', 'F', 4200.00, '555555555', 10);

-- Dependentes
INSERT INTO DEPENDENTE (ESSN, NOME_DEPENDENTE, SEXO, DATANASC, PARENTESCO) VALUES
('111111111', 'Alice', 'F', '2015-06-10', 'Filha'),
('222222222', 'Carlos', 'M', '2010-04-22', 'Filho'),
('333333333', 'Diana', 'F', '2018-11-30', 'Filha');

-- Projetos
INSERT INTO PROJETO (PNUMERO, PJNOME, PLOCALIZACAO, DNUM) VALUES
(100, 'Produtox', 'Sede', 5),
(200, 'Alpha', 'Filial', 5),
(300, 'Beta', 'Sede', 10);

-- Trabalha_em
INSERT INTO TRABALHA_EM (ESSN, PNO, HORAS) VALUES
('111111111', 100, 12),
('111111111', 200, 5),
('111111111', 300, 8),
('222222222', 100, 8),
('222222222', 200, 5),
('333333333', 100, 10),
('444444444', 200, 7),
('555555555', 300, 6);

-- CONSULTAS

-- a) Empregados do departamento 5 que trabalham mais de 10 horas no projeto 'Produtox'
SELECT e.PNOME, e.MINICIAL, e.UNOME, e.DNO AS DEPARTAMENTO, p.PJNOME AS PROJETO, t.HORAS
FROM EMPREGADO AS e
JOIN TRABALHA_EM t ON e.SSN = t.ESSN
JOIN PROJETO p ON t.PNO = p.PNUMERO
WHERE e.DNO = 5 AND p.PJNOME = 'Produtox' AND t.HORAS > 10;

-- b) Empregados que têm dependente com mesmo primeiro nome
SELECT e.PNOME, e.MINICIAL, e.UNOME, d.NOME_DEPENDENTE, d.PARENTESCO
FROM EMPREGADO AS e
JOIN DEPENDENTE d ON e.SSN = d.ESSN
WHERE e.PNOME = d.NOME_DEPENDENTE;

-- c) Empregados supervisionados por 'Franklin Wong'
SELECT e.PNOME, e.MINICIAL, e.UNOME, s.PNOME AS SUPERVISOR, s.UNOME AS SOBRENOME_SUPERVISOR
FROM EMPREGADO AS e
JOIN EMPREGADO AS s ON e.SUPERSSN = s.SSN
WHERE s.PNOME = 'Franklin' AND s.UNOME = 'Wong';

-- d) Para cada projeto, liste o nome e o total de horas gastas
SELECT p.PJNOME, SUM(t.HORAS) AS TOTAL_HORAS
FROM PROJETO AS p
LEFT JOIN TRABALHA_EM AS t ON p.PNUMERO = t.PNO
GROUP BY p.PJNOME;

-- e) Empregados que trabalham em todos os projetos
SELECT e.PNOME, e.MINICIAL, e.UNOME, COUNT(DISTINCT t.PNO) AS QTDE_PROJETOS
FROM EMPREGADO AS e
JOIN TRABALHA_EM AS t ON e.SSN = t.ESSN
GROUP BY e.SSN
HAVING COUNT(DISTINCT t.PNO) = (SELECT COUNT(*) FROM PROJETO);

-- f) Empregados que não trabalham em nenhum projeto
SELECT e.PNOME, e.MINICIAL, e.UNOME, e.DNO AS DEPARTAMENTO
FROM EMPREGADO AS e
LEFT JOIN TRABALHA_EM t ON e.SSN = t.ESSN
WHERE t.ESSN IS NULL;

-- g) Para cada departamento, nome e média salarial
SELECT d.DNAME, AVG(e.SALARIO) AS MEDIA_SALARIAL, COUNT(e.SSN) AS QTD_EMPREGADOS
FROM DEPARTAMENTO AS d
JOIN EMPREGADO AS e ON d.DNUMERO = e.DNO
GROUP BY d.DNAME;

-- h) Média salarial dos empregados do sexo feminino
SELECT SEXO, AVG(SALARIO) AS MEDIA_SALARIAL
FROM EMPREGADO
WHERE SEXO = 'F';