SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS EMPRESTIMO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS FILIAL;
DROP TABLE IF EXISTS AUTORES_LIVRO;

SET FOREIGN_KEY_CHECKS = 1;

-- CRIAÇÃO DE TABELAS

CREATE TABLE AUTORES_LIVRO (
  ID_LIVRO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITULO VARCHAR(150) NOT NULL,
  NOME_EDITORA VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE FILIAL (
  ID_FILIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_FILIAL VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(200) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE USUARIO (
  ID_CARTAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(200),
  TELEFONE VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE EMPRESTIMO (
  ID_EMPRESTIMO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATA_RETIRADA DATE NOT NULL,
  DATA_DEVOLUCAO DATE,
  ID_LIVRO INT NOT NULL,
  ID_CARTAO INT NOT NULL,
  ID_FILIAL INT NOT NULL,
  FOREIGN KEY (ID_LIVRO) REFERENCES AUTORES_LIVRO(ID_LIVRO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_CARTAO) REFERENCES USUARIO(ID_CARTAO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

-- INSERÇÕES

INSERT INTO AUTORES_LIVRO (TITULO, NOME_EDITORA) VALUES
('Banco de Dados Essencial', 'Editora Ciência Moderna'),
('Algoritmos em C', 'Bookman'),
('Redes de Computadores', 'Pearson'),
('Engenharia de Software', 'Campus'),
('Inteligência Artificial', 'Elsevier');

INSERT INTO FILIAL (NOME_FILIAL, ENDERECO) VALUES
('Central', 'Av. Paulista, 1000 - São Paulo, SP'),
('Sharpstown', 'Rua das Palmeiras, 200 - Rio de Janeiro, RJ'),
('Centro BH', 'Praça Sete, 50 - Belo Horizonte, MG');

INSERT INTO USUARIO (NOME, ENDERECO, TELEFONE) VALUES
('Mariana Silva', 'Rua das Flores, 120 - São Paulo, SP', '(13) 9 9167-9535'),
('Carlos Souza', 'Av. Brasil, 2300 - Rio de Janeiro, RJ', '(21) 9 8765-4321'),
('Ana Oliveira', 'Rua da Bahia, 300 - Belo Horizonte, MG', '(31) 9 9988-7766'),
('João Pereira', 'Rua Goiás, 150 - Belo Horizonte, MG', '(31) 9 8877-6655');

INSERT INTO EMPRESTIMO (DATA_RETIRADA, DATA_DEVOLUCAO, ID_LIVRO, ID_CARTAO, ID_FILIAL) VALUES
(DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY), DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY), 1, 1, 1),
(DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY), CURRENT_DATE(), 2, 2, 2),
(CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), 3, 3, 3),
(CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), 4, 1, 1),
(CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), 5, 1, 1),
(CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), 2, 1, 1),
(CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), 3, 1, 1),
(CURRENT_DATE(), DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), 1, 1, 1);

-- CONSULTAS
-- a) Usuários que NÃO tenham nenhum registro de empréstimo
SELECT u.NOME
FROM USUARIO AS u
LEFT JOIN EMPRESTIMO AS e ON u.ID_CARTAO = e.ID_CARTAO
WHERE e.ID_EMPRESTIMO IS NULL;

-- b) Livros emprestados em Sharpstown e cuja data de devolução seja hoje
SELECT al.TITULO, u.NOME, u.ENDERECO
FROM EMPRESTIMO AS e
JOIN AUTORES_LIVRO AS al ON e.ID_LIVRO = al.ID_LIVRO
JOIN USUARIO AS u ON e.ID_CARTAO = u.ID_CARTAO
JOIN FILIAL AS f ON e.ID_FILIAL = f.ID_FILIAL
WHERE f.NOME_FILIAL = 'Sharpstown'
  AND e.DATA_DEVOLUCAO = CURRENT_DATE();

-- c) Para cada filial, recupere nome e número total de livros emprestados
SELECT f.NOME_FILIAL, COUNT(e.ID_EMPRESTIMO) AS total_emprestimos
FROM FILIAL AS f
LEFT JOIN EMPRESTIMO AS e ON f.ID_FILIAL = e.ID_FILIAL
GROUP BY f.ID_FILIAL, f.NOME_FILIAL
ORDER BY f.NOME_FILIAL;

-- d) Usuários que tenham pego emprestado mais de 5 livros
SELECT u.NOME, u.ENDERECO, COUNT(e.ID_EMPRESTIMO) AS total_emprestimos
FROM USUARIO AS u
JOIN EMPRESTIMO AS e ON u.ID_CARTAO = e.ID_CARTAO
GROUP BY u.ID_CARTAO, u.NOME, u.ENDERECO
HAVING COUNT(e.ID_EMPRESTIMO) > 5
ORDER BY total_emprestimos DESC;

